feat: Add Immutable Seaport and Immutable Signable Zone to repository
immutable/immutable-seaport pull request #1
Opened 2023-07-31 22:00 UTC by Sam-Jeston

2023-07-31 23:31 UTC, lfportal requested changes

2023-07-31 23:31 UTC, lfportal commented on contracts/ImmutableSeaport.sol
> +// contract ImmutableSeaport is Consideration {
```suggestion
```

2023-07-31 23:31 UTC, lfportal commented on contracts/ImmutableSeaport.sol
> +    mapping(address => bool) public immutableZones;
**Nit Suggestion:** Whilst this is Immutable's Seaport fork, the `immutable*` prefix doesn't help describe the intended behaviour. Could we change this to something like `allowedZones`?

2023-07-31 23:31 UTC, lfportal commented on contracts/ImmutableSeaport.sol
> +    error InvalidZone(address zone);
**Suggestion:** More of a question - Is it a recommended pattern to contain `error` and `event` definitions in a separate `.sol` file? I've seen this pattern in many contracts but haven't thought of an obvious reason for doing so.

2023-07-31 23:31 UTC, lfportal commented on contracts/ImmutableSeaport.sol
> +    function addImmutableZone(
**Suggestion:** Not a standard or anything, but this is functionally similar to `ERC721.setApprovalForAll`. Could we follow a similar function signature and name? Something like `setAllowedZone(address zone, bool allowed)` and drop the `removeImmutableZone` function altogether?

2023-07-31 23:31 UTC, lfportal commented on contracts/conduit/ImmutableConduitController.sol
> +contract ImmutableConduitController is ConduitController{}
**Question:** If we are not making modifications, could we drop this and import only to deploy `ConduitController`?

2023-07-31 23:31 UTC, lfportal commented on contracts/validators/ImmutableReadOnlyOrderValidator.sol
> +contract ImmutableReadOnlyOrderValidator is ReadOnlyOrderValidator {}
**Question:** Similar to above, if we are not making modifications, could we drop this and import only to deploy `ReadOnlyValidator`?

2023-07-31 23:31 UTC, lfportal commented on contracts/validators/ImmutableSeaportValidator.sol
> +contract ImmutableSeaportValidator is SeaportValidator {
**Question:** Similar to above, if we are not making modifications, could we drop this and import only to deploy `SeaportValidator`?

2023-07-31 23:31 UTC, lfportal commented on contracts/validators/ImmutableSeaportValidatorHelper.sol
> +contract ImmutableSeaportValidatorHelper is SeaportValidatorHelper {}
**Question:** Similar to above, if we are not making modifications, could we drop this and import only to deploy `SeaportValidatorHelper`?

2023-07-31 23:31 UTC, lfportal commented on hardhat.config.ts
> +      // allowUnlimitedContractSize: true,
**Suggestion:** Can we action this `TODO` now?

2023-07-31 23:31 UTC, lfportal commented on package.json
> +    "seaport": "https://github.com/immutable/seaport.git#chore/compile-test-helpers"
**Question:** Is this still necessary?

2023-07-31 23:48 UTC, Sam-Jeston commented on package.json
> +    "seaport": "https://github.com/immutable/seaport.git#chore/compile-test-helpers"
ooo good spot, ty

2023-08-01 01:18 UTC, Sam-Jeston commented on contracts/ImmutableSeaport.sol
> +    error InvalidZone(address zone);
I'm really not sure - I did a bit of reading to try answer this, checking various "Solidity best practices" guides that people have written, none of them explicitly mention this. Happy to make an ImmutableEventsAndErrors.sol file and move them, but not sure its necessary either

2023-08-01 01:19 UTC, Sam-Jeston commented on contracts/ImmutableSeaport.sol
> +    function addImmutableZone(
Yeh I think that will be nicer, this was just the OG rollups implementation as I understand it

2023-08-01 03:43 UTC, Sam-Jeston commented on contracts/conduit/ImmutableConduitController.sol
> +contract ImmutableConduitController is ConduitController{}
Indeed we could, but I actually liked how explicit the `Immutable*` wrapper is - how strongly do you feel about changing this?

2023-08-01 03:43 UTC, Sam-Jeston commented on contracts/ImmutableSeaport.sol
> +    function addImmutableZone(
Actioned in https://github.com/immutable/immutable-seaport/pull/1/commits/e0fad2022d0c3e4e05e6870220cdfa7e465ef6bf

2023-08-01 23:29 UTC, Sam-Jeston commented on contracts/conduit/ImmutableConduitController.sol
> +contract ImmutableConduitController is ConduitController{}
After further consideration, I agree, and have done as suggested

2023-08-01 23:29 UTC, lfportal approved these changes

2023-08-01 23:32 UTC, merged